# Generated by Django 5.1.3 on 2024-11-19 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_rename_course_grade_course_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['id']},
        ),
    ]
