# Generated by Django 5.1.3 on 2024-11-17 22:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_enrollment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="teacher",
            new_name="teacher_id",
        ),
        migrations.RenameField(
            model_name="enrollment",
            old_name="course",
            new_name="course_id",
        ),
        migrations.RenameField(
            model_name="enrollment",
            old_name="student",
            new_name="student_id",
        ),
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together={("student_id", "course_id")},
        ),
    ]
