# Generated by Django 5.1.3 on 2024-11-17 23:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attendance",
            old_name="course",
            new_name="course_id",
        ),
        migrations.RenameField(
            model_name="attendance",
            old_name="student",
            new_name="student_id",
        ),
    ]
